I PVC You Pee
RIT-EVT/PVC pull request #3
Opened 2023-01-27 01:55 UTC by bencerr

Used SPI to read the voltage obtained from the MAX22530, made a driver to test the registers (1 - 8).

2023-01-28 16:16 UTC, mjmagee991 commented
![](https://github.trello.services/images/mini-trello-icon.png) [MAX ADC Driver](https://trello.com/c/2WBigAMe/7-max-adc-driver)

2023-01-28 16:51 UTC, mjmagee991 requested changes
There's one little issue with the driver, and a couple nitpicks with your documentation. Otherwise, looks pretty good

2023-01-28 16:51 UTC, mjmagee991 commented on include/PreCharge/dev/MAX22530.hpp
> + * Handles reading the voltage values & converting it to decivolts from the
NIT: Goes into a bit too much detail. Doesn't need to go beyond "Handles reading voltage data from the MAX22530 ADC

2023-01-28 16:51 UTC, mjmagee991 commented on include/PreCharge/dev/MAX22530.hpp
> +     * to decivolts.
NIT: There should be a newline between the summary and parameters in each method comment

2023-01-28 16:51 UTC, mjmagee991 commented on include/PreCharge/dev/MAX22530.hpp
> +}// namespace PreCharge
Add a newline to the end of the file

2023-01-28 16:51 UTC, mjmagee991 commented on include/PreCharge/dev/MAX22530.hpp
> +    /// The SPI interface to read from
These 1-line comments should follow this format:
`/** Documentation documentation */`

2023-01-28 16:51 UTC, mjmagee991 commented on include/PreCharge/dev/MAX22530.hpp
> +     * @return The conversion of the ADC value into temperature
This comment should be updated

2023-01-28 16:51 UTC, mjmagee991 commented on src/PreCharge/dev/MAX22530.cpp
> +}// namespace PreCharge
Add a newline to the end of the file

2023-01-28 16:51 UTC, mjmagee991 commented on src/PreCharge/dev/MAX22530.cpp
> +    uint8_t result = (((uint32_t) count) * 1098) / 40960;// 1.8 * 61 (* 10 for 1.8 to make it fix point) 1.8 is the reference voltage, 61 is voltage divider ratio
```suggestion
    uint8_t result = (((uint32_t) count) * 1098) / 40960;// 1.8 * 61 (* 10 for 1.8 to make it fixed point) 1.8 is the reference voltage, 61 is voltage divider ratio
```

2023-01-28 16:51 UTC, mjmagee991 commented on targets/MAX22530/main.cpp
> + * This example prints out voltage reading from the MAX22530 ADC converter
```suggestion
 * This example prints out voltage reading from the MAX22530 ADC
```
NIT: The C in ADC stands for converter

2023-01-28 16:51 UTC, mjmagee991 commented on targets/MAX22530/main.cpp
> +            uart.printf("Register 0x%x: %d\r\n", reg, MAX.readVoltage(reg << 2));
Put this `<< 2` inside the `readVoltage()` code, so the user doesn't have to left shift every single time they call this function.

2023-01-31 00:23 UTC, AarC10 approved these changes
Looks good besides what Matt mentioned

2023-01-31 01:37 UTC, ActuallyZach approved these changes

2023-01-31 03:17 UTC, DeLozM8 approved these changes

2023-02-01 23:26 UTC, mjmagee991 approved these changes
Nice job

2023-02-01 23:26 UTC, mjmagee991 commented on include/PreCharge/dev/MAX22530.hpp
> +     * @param[in] spi
This variable should have a short description

2023-02-01 23:26 UTC, mjmagee991 requested changes
One small issue

2023-02-03 04:09 UTC, mjmagee991 approved these changes
Looks good

2023-02-04 17:29 UTC, merged