[P]retty [V]alue [C]ommunications
RIT-EVT/PVC pull request #4
Opened 2023-02-07 01:38 UTC by zsteig

New format for CAN messages to allow integration team to monitor PVC state

2023-02-09 14:39 UTC, mjmagee991 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PVC PDO Validation](https://trello.com/c/XjcBbsXh/45-pvc-pdo-validation)

2023-02-10 01:45 UTC, DeLozM8 approved these changes

2023-02-11 15:12 UTC, mjmagee991 requested changes
Looks great. I have a couple minor nitpicks, but they shouldn't take long

2023-02-11 15:12 UTC, mjmagee991 commented on include/PreCharge/PreCharge.hpp
> +     *
NIT: Delete this extra line

2023-02-11 15:12 UTC, mjmagee991 commented on src/PreCharge/PreCharge.cpp
>  void PreCharge::sendChangePDO() {
This method needs documentation in the `.hpp` file. Also, it should probably be made private.

2023-02-11 15:12 UTC, mjmagee991 commented on src/PreCharge/PreCharge.cpp
> +                                           static_cast<unsigned short>(contStatus) << 4 | static_cast<unsigned short>(apmStatus)};
```suggestion
                                           static_cast<unsigned short>(contStatus) << 4 | static_cast<unsigned short>(apmStatus),};
```
Adding a comma here will fix the auto-formatting

2023-02-14 01:08 UTC, mjmagee991 approved these changes
Looks good

2023-02-14 01:35 UTC, merged