PVCleanup
RIT-EVT/PVC pull request #8
Opened 2023-12-08 00:45 UTC by dwp1084

2023-12-09 03:25 UTC, mjmagee991 requested changes
Seeing it all laid out like this, I think it might be easier to maintain and understand what's going on if the DEV1 and KEV1N classes are completely independent of each other. As it is now, you'd have to jump between PreChargeBase and PreCharge to follow the flow of logic, which is going to make maintaining it a bit of a pain. Ultimately, though, it's up to you whether you want these classes to be separate or together, because you're the person who has to maintain it.

The one other argument I'll give for separating them out is that it will let us merge this branch without doing any additional testing because the main PreCharge code won't have changed. If you do split things up like this, we're going to have to do quite a bit of testing to make sure everything is still working.

No solution is ideal, but I'd like to hear your thoughts.

2024-01-27 13:54 UTC, mjmagee991 approved these changes
Looks great!

2024-01-29 02:53 UTC, aclowmclaughlin approved these changes
Looks good, I think!

2024-01-29 02:53 UTC, aclowmclaughlin commented on targets/PreCharge/main.cpp
> +* NOTE: For this sample, every non-extended (so 11 bit CAN IDs) will be
Should you have the "for this sample" notes in here?

2024-01-29 02:53 UTC, aclowmclaughlin commented on targets/PreChargeKEV1N/main.cpp
> +extern "C" void CONodeFatalError(void) {
This stuff will be unnecessary eventually with Taylor's CanOpen changes, but I assume it's all good for now.

2024-02-07 15:15 UTC, merged